---
# EXAMPLE_5: Break convergence by instealling a pakage that doesn't exist
# - name: "main | install it_just_works"
#   yum:
#     name: it_just_works
#     state: present

- name: "main | install which"
  yum:
    name: which
    state: present

- name: "main | install iproute"
  yum:
    name: iproute
    state: present

- name: "main | include repos tasks"
  include_tasks: repos.yml

- name: "main | include nginx tasks"
  include_tasks: nginx.yml

- name: "main | include python3 tasks"
  include_tasks: python3.yml

# EXAMPLE_3: introduce syntax error (invalid parameter)
- name: "main | include app tasks"
  include_tasks: app.yml
#  cant_do_this: true
