---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    # EXAMPLE_4: break 'molecule create' by changing 'latest' to 'best'
    # because you should always run the best Docker image
    # image: centos/systemd:best
    image: centos/systemd:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    exposed_ports:
      - 81/tcp
    published_ports:
      - 0.0.0.0:80:81/tcp
    command: /usr/sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # EXAMPLE_6: idempotence is hard.  Look at molecule scenarios for CI.
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
